# Generated by Django 4.2.1 on 2023-11-29 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleVisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('score', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, null=True, verbose_name='Failo pavadinimas')),
                ('image_file', models.ImageField(null=True, upload_to='images/', verbose_name='Ikelkite faila')),
                ('notes', models.TextField(max_length=500, null=True, verbose_name='Uzrasai')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('lon', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=50, null=True)),
                ('map_description', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('upload_model', models.ManyToManyField(blank=True, related_name='uploadmodel', to='file_system.imageuploadmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vision_model', models.ManyToManyField(blank=True, related_name='visionmodel', to='file_system.googlevisionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MapPointers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('map_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_system.mapcreation')),
            ],
        ),
        migrations.AddField(
            model_name='googlevisionmodel',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_system.imageuploadmodel'),
        ),
        migrations.AddField(
            model_name='googlevisionmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
