# Generated by Django 4.2.1 on 2023-11-30 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointers',
            name='image_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_system.imageuploadmodel'),
        ),
    ]
