# Generated by Django 4.2.1 on 2023-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0002_imageuploadmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
