# Generated by Django 4.2.1 on 2023-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0003_mappointers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcreation',
            name='upload_model',
        ),
        migrations.RemoveField(
            model_name='mapcreation',
            name='vision_model',
        ),
        migrations.AlterField(
            model_name='mapcreation',
            name='map_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
