# Generated by Django 4.2.1 on 2023-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0004_googlevisionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlevisionmodel',
            old_name='coordinates',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='googlevisionmodel',
            name='longtitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Ikelkite faila'),
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Failo pavadinimas'),
        ),
    ]
