# Generated by Django 4.2.1 on 2023-06-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0005_rename_coordinates_googlevisionmodel_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlevisionmodel',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
