# Generated by Django 4.2.1 on 2023-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0006_rename_longtitude_googlevisionmodel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlevisionmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
