# Generated by Django 4.2.1 on 2023-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0007_googlevisionmodel_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlevisionmodel',
            name='score',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True),
        ),
    ]
