# Generated by Django 4.2.1 on 2023-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0008_alter_googlevisionmodel_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='notes',
            field=models.TextField(max_length=500, null=True, verbose_name='Uzrasai'),
        ),
    ]
